# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emoji < Formula
  desc ""
  homepage ""
  version "0.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fmierlo/emoji/releases/download/v0.0.0/emoji_0.0.0_darwin_amd64.tar.gz"
      sha256 "02652ae9cf40ac7bc9d59b7401c80a1644c74f125e15c9e6e56b73d8515f85b0"

      def install
        bin.install "e"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fmierlo/emoji/releases/download/v0.0.0/emoji_0.0.0_darwin_arm64.tar.gz"
      sha256 "02652ae9cf40ac7bc9d59b7401c80a1644c74f125e15c9e6e56b73d8515f85b0"

      def install
        bin.install "e"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/fmierlo/emoji/releases/download/v0.0.0/emoji_0.0.0_linux_amd64.tar.gz"
      sha256 "02652ae9cf40ac7bc9d59b7401c80a1644c74f125e15c9e6e56b73d8515f85b0"

      def install
        bin.install "e"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/fmierlo/emoji/releases/download/v0.0.0/emoji_0.0.0_linux_armv7.tar.gz"
      sha256 "02652ae9cf40ac7bc9d59b7401c80a1644c74f125e15c9e6e56b73d8515f85b0"

      def install
        bin.install "e"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fmierlo/emoji/releases/download/v0.0.0/emoji_0.0.0_linux_arm64.tar.gz"
      sha256 "02652ae9cf40ac7bc9d59b7401c80a1644c74f125e15c9e6e56b73d8515f85b0"

      def install
        bin.install "e"
      end
    end
  end
end
