# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emoji < Formula
  desc ""
  homepage ""
  version "0.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fmierlo/emoji/releases/download/v0.0.0/emoji_0.0.0_darwin_amd64.tar.gz"
      sha256 "e0abce2d9509c02548fdde7e94a1b6e9ae7cc92a8574997a18bb4e0da94b5a46"

      def install
        bin.install "e"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fmierlo/emoji/releases/download/v0.0.0/emoji_0.0.0_darwin_arm64.tar.gz"
      sha256 "e0abce2d9509c02548fdde7e94a1b6e9ae7cc92a8574997a18bb4e0da94b5a46"

      def install
        bin.install "e"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/fmierlo/emoji/releases/download/v0.0.0/emoji_0.0.0_linux_amd64.tar.gz"
      sha256 "e0abce2d9509c02548fdde7e94a1b6e9ae7cc92a8574997a18bb4e0da94b5a46"

      def install
        bin.install "e"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/fmierlo/emoji/releases/download/v0.0.0/emoji_0.0.0_linux_armv7.tar.gz"
      sha256 "e0abce2d9509c02548fdde7e94a1b6e9ae7cc92a8574997a18bb4e0da94b5a46"

      def install
        bin.install "e"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fmierlo/emoji/releases/download/v0.0.0/emoji_0.0.0_linux_arm64.tar.gz"
      sha256 "e0abce2d9509c02548fdde7e94a1b6e9ae7cc92a8574997a18bb4e0da94b5a46"

      def install
        bin.install "e"
      end
    end
  end
end
